### ISSUE TITLE
Add README and Templates

### ISSUE THREAD

**Issue by dcwalk** [archivers-space/task-mgmt#12]
Make sure this repo has the following files:
- [x] Readme `README.md`
   - [ ] Repo Badges for: Github Project, Slack, License
   - [ ] 1-3 sentence description of repository contents
   - [ ] Getting Involved section
   - [x] Development section
- [x] License -- `LICENSE`
- [x] Contributing Guidelines (minimal and pointing to org-wide) `.github/CONTRIBUTING.md`
- [x] Issue Template -- `.github/ISSUE_TEMPLATE.md`
- [ ] GitHub Description from 1-3 sentence readme blurb

This issue forms part of [a project-wide meta-issue](https://github.com/datatogether/roadmap/issues/37)

**Comment by titaniumbones** [comment]
closed in #13

**Comment by dcwalk** [comment]
This is done 🎉
